# Generated by Django 4.1.4 on 2023-04-06 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_date', models.DateTimeField(null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('groupname', models.CharField(max_length=2000, null=True)),
                ('number', models.CharField(max_length=2000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_date', models.DateTimeField(null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('manufacturer_name', models.CharField(max_length=2000, null=True)),
                ('code', models.CharField(max_length=2000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_date', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_date', models.DateTimeField(null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('name', models.CharField(max_length=2000, null=True)),
                ('code', models.CharField(max_length=2000, null=True)),
                ('u_group', models.CharField(max_length=2000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_date', models.DateTimeField(null=True)),
                ('expration_date', models.DateTimeField(null=True)),
                ('period', models.CharField(blank=True, choices=[('month', 'month'), ('season', 'season'), ('year', 'year')], max_length=50, null=True)),
                ('summa', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
