# Generated by Django 4.1.4 on 2023-04-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_edited_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
