# Generated by Django 4.1.4 on 2023-04-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_category_alter_product_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='orders',
            field=models.IntegerField(default=0),
        ),
    ]
