# Generated by Django 4.1.4 on 2023-04-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sale_active_sale_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='name',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
