# Generated by Django 4.1.4 on 2023-04-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_do_num_order_doc_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='summa',
            field=models.FloatField(default=0),
        ),
    ]
