# Generated by Django 4.1.4 on 2023-04-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_order_summa'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_sum',
            field=models.FloatField(default=0),
        ),
    ]
