# Generated by Django 4.1.4 on 2023-04-13 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_total_sum_order_u_sumuzs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='gift_ptoduct',
            new_name='gift_product',
        ),
    ]
