# Generated by Django 4.1.4 on 2023-04-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_gift_ptoduct_sale_gift_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersale',
            name='order_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
