# Generated by Django 4.1.4 on 2023-04-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_usersale_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordetdetail',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordetdetail',
            name='total_uzs',
            field=models.IntegerField(default=0),
        ),
    ]
