# Generated by Django 4.1.4 on 2023-04-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_ordetdetail_total_ordetdetail_total_uzs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdetDetail',
            new_name='OrderDetail',
        ),
    ]
