# Generated by Django 4.1.4 on 2023-04-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_orderdetail_total_alter_orderdetail_total_uzs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='total',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='total_uzs',
            field=models.FloatField(default=0, null=True),
        ),
    ]
