# Generated by Django 4.2 on 2023-04-26 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_orderdetail_total_alter_orderdetail_total_uzs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercashback',
            old_name='expration_date',
            new_name='expiration_date',
        ),
    ]
