# Generated by Django 4.2 on 2023-05-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_expration_date_usercashback_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('period', models.CharField(blank=True, choices=[('month', 'month'), ('season', 'season'), ('year', 'year')], max_length=50, null=True)),
                ('summa', models.IntegerField(default=0)),
            ],
        ),
    ]
