# Generated by Django 4.2 on 2023-05-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_order_u_sumuzs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashback',
            name='persent',
            field=models.IntegerField(default=1),
        ),
    ]
