# Generated by Django 4.2 on 2023-06-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_promocode_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_sale',
            field=models.IntegerField(default=0),
        ),
    ]
