# Generated by Django 4.2 on 2023-07-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='summa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
