# Generated by Django 4.2 on 2023-07-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_story_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercashbackhistory',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
