# Generated by Django 4.2 on 2023-07-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_usercashbackhistory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='pay_type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
