# Generated by Django 4.2 on 2023-07-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_userlocations_latitude_userlocations_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order_sale',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
