# Generated by Django 4.2 on 2023-07-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_product_order_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='pay_type',
        ),
        migrations.AddField(
            model_name='order',
            name='pay_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
