# Generated by Django 4.2 on 2023-08-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercashbackhistory',
            name='date',
        ),
    ]
