# Generated by Django 4.2 on 2023-09-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_sale_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
