# Generated by Django 4.2 on 2023-11-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_product_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercashbackhistory',
            name='order',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
