# Generated by Django 4.2 on 2024-01-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_usercashbackhistory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercashbackhistory',
            name='doc_entry',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='usercashbackhistory',
            name='doc_num',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
