# Generated by Django 4.2 on 2024-01-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_usercashbackhistory_doc_entry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
