# Generated by Django 4.2 on 2024-04-23 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_salesemployee_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='clinet_phone_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='manager_phone_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='moll',
        ),
        migrations.AddField(
            model_name='order',
            name='sales_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.salesemployee'),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.warehouse'),
        ),
    ]
