# Generated by Django 4.2 on 2024-04-23 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_remove_order_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesemployee',
            name='ware_house',
        ),
        migrations.AddField(
            model_name='salesemployee',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.warehouse'),
        ),
    ]
