# Generated by Django 4.1.4 on 2023-04-04 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='megauser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='megauser',
            name='username',
        ),
    ]
