# Generated by Django 4.1.4 on 2023-04-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_megauser_managers_remove_megauser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='megauser',
            name='card_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='megauser',
            name='card_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='megauser',
            name='odata_etag',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='megauser',
            name='otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
