# Generated by Django 4.1.4 on 2023-04-06 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_megauser_card_code_megauser_card_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='megauser',
            name='odata_etag',
        ),
    ]
