# Generated by Django 4.2 on 2023-05-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_megauser_email_alter_megauser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='megauser',
            name='all_cashback',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='megauser',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
    ]
