# Generated by Django 4.2 on 2023-08-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_megauser_all_cashback_alter_megauser_is_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='megauser',
            name='all_cashback',
            field=models.IntegerField(default=0),
        ),
    ]
