# Generated by Django 4.2 on 2023-09-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_megauser_all_cashback'),
    ]

    operations = [
        migrations.AddField(
            model_name='megauser',
            name='sale_cashback',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
